[package]
name = "wf-config"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
name = "wf_config"

[dependencies]
serde = { workspace = true }
toml = { workspace = true }
anyhow = { workspace = true }
glob = "0.3"

[dev-dependencies]
serde_json = "1.0"
