version = "1.0"

[sink_group]
name = "security_output"
windows = ["security_*"]

[[sink_group.sinks]]
connect = "file_json"
name = "sec_file"

[sink_group.sinks.params]
path = "alerts/security_alerts.jsonl"
