[package]
name = "wf-lang"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
name = "wf_lang"

[dependencies]
winnow = { workspace = true }
anyhow = { workspace = true }
regex-syntax = "0.8"
